name: Example

on:
  push:

jobs:
  mysql:
    name: MySQL Test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup mysql-action
        run: sudo systemctl start mysql.service

      - name: Check MySQL ver
        run: sudo mysql --version

      #- name: Set Charset
      #  run: mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "set character_set_database=utf8; set character_set_server=utf8;"
        
      #- name: show charset
      #  run: |
      #    sleep 30
      #    mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "show variables like 'chara%'"

      - name: DML test
        run: >-
          mysql -h 127.0.0.1 --port 3306 -uroot -proot 
          -e "
          use mysql;
          create table test_table(
            id int(11) auto_increment not null,
            name varchar(30) not null,
            primary key(id)
          );
          alter table test_table convert to character set utf8;
          show variables like 'chara%'
          insert into test_table values(12345, '伊藤博文');
          select * from test_table;
          "