name: Example

on:
  push:

jobs:
  mysql:
    name: MySQL Test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup mysql-action
        run: sudo systemctl start mysql.service

      - name: Check MySQL ver
        run: sudo mysql --version

      - name: DML test
        run: >-
          mysql -h 127.0.0.1 --port 3306 -uroot -proot 
          -e "
          create user 'keishi'@'localhost' identified by 'keishi';
          grant all privileges on * . * 'keishi'@'localhost';
          flush privileges;
          use mysql;
          create table test_table(
            id int(11) auto_increment not null,
            name varchar(30) not null,
            primary key(id)
          );
          alter table test_table convert to character set utf8;
          show create table test_table;
          insert into test_table values(12345, '伊藤博文');
          insert into test_table values(23456, '伊能忠敬');
          select * from test_table;
          "

# 予備
      #- name: DML test
      #  run: >-
      #    mysql -h 127.0.0.1 --port 3306 -uroot -proot 
      #    -e "
      #    use mysql;
      #    create table test_table(
      #      id int(11) auto_increment not null,
      #      name varchar(30) not null,
      #      primary key(id)
      #    );
      #    alter table test_table convert to character set utf8;
      #    show create table test_table;
      #    insert into test_table values(12345, '伊藤博文');
      #    insert into test_table values(23456, '伊能忠敬');
      #    select * from test_table;
      #    "