name: Example

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup mysql-action
        run: sudo systemctl start mysql.service
      #  uses: mirromutth/mysql-action@v1.1
      #  with:
      #    host port: 3306 # Optional, default value is 3306. The port of host
      #    container port: 3306 # Optional, default value is 3306. The port of container
      #    character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
      #    collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
      #    mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
      #    mysql database: 'test_db' # Optional, default value is "test". The specified database which will be create
      #    mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: show charset
        run: |
          sleep 30
          mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "show variables like 'chara%'"
      - name: DML test
        run: >-
          mysql -h 127.0.0.1 --port 3306 -uroot -proot 
          -e "
          use test_db;
          create table test_table(
            id int(11) auto_increment not null,
            name varchar(30) not null,
            primary key(id)
          );
          insert into test_table values(12345, '伊藤博文');
          select * from test_table;
          "
#jobs:
#  job-with-mysql-5_7:
#    runs-on: ubuntu-20.04
#    services:
#      db:
#        image: mysql:5.7
#        ports:
#          - 3306:3306
#        env:
#          MYSQL_ROOT_PASSWORD: root_password
#          MYSQL_DATABASE: foo
#          MYSQL_USER: user1
#          MYSQL_PASSWORD: user1_password
#        options: >-
#          --health-cmd "mysqladmin ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#    steps:
#      - name: Show Docker containers
#        run: docker ps -a
      #- name: Show databases for root user
      #  run: >-
      #    mysql --protocol=tcp -h localhost -P 3306 -u root -proot_password
      #    -e "
      #    SHOW DATABASES;
      #    USE foo;
      #    CREATE TABLE name_age_list(
      #      id INT(11) AUTO_INCREMENT NOT NULL,
      #      name VARCHAR(30) NOT NULL,
      #      age INT(3) NOT NULL,
      #      PRIMARY KEY(id)
      #    );
      #    DESC name_age_list;
      #    INSERT INTO name_age_list VALUES(12345, 'keishi', 35);
      #    INSERT INTO name_age_list VALUES(23456, '野口', 35);
      #    SELECT * FROM name_age_list;
      #    "
      #- name: Charset Set
      #  run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot_password -e "SET character_set_database=utf8mb4;"

      #- name: Show Varialbles
      #  run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot_password -e "show global variables like '%char%';"